# Generated by Django 5.2.1 on 2025-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
